/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ClienteChatBOX;

import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JDialog;

/**
 *
 * @author Carlos Bautista
 * @CanalOficcial Cisco GT
 * @Carrera Ingenieria en Sistemas y TICs
 * 
 */

public class ConfiguracionSala extends javax.swing.JFrame 
{

    /** Creates new form ConfiguracionSala */
    public ConfiguracionSala() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
        Container c = this.getContentPane();
            c.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        
            gbc.insets = new Insets(20, 20, 0, 50);
        
                gbc.gridx = 0;
                     gbc.gridy = 0;
                c.add(lbUsuario, gbc);
        
            gbc.gridx = 0;
        gbc.gridy = 1;
            c.add(lbHost, gbc);
        
                gbc.gridx = 0;
                    gbc.gridy = 2;
                c.add(lbPuerto, gbc);
        
             gbc.ipadx = 85;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        
            gbc.gridx = 1;
                gbc.gridy = 0;
                    c.add(tfUsuario, gbc);
        
                gbc.gridx = 1;
            gbc.gridy = 1;
        c.add(tfHost, gbc);
        
            gbc.gridx = 1;
                gbc.gridy = 2;
        c.add(tfPuerto, gbc);
        
            gbc.gridx = 0;
                 gbc.gridy = 3;
                    gbc.gridwidth = 2;
                gbc.insets = new Insets(20, 20, 20, 20);
        c.add(btAceptar, gbc);
        
        this.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE); // Deshabilita el boton de cierre de la ventana 
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsuario = new javax.swing.JLabel();
        lbHost = new javax.swing.JLabel();
        lbPuerto = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        tfHost = new javax.swing.JTextField();
        tfPuerto = new javax.swing.JTextField();
        btAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUsuario.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/business_application.png"))); // NOI18N
        lbUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lbHost.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbHost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ip1.png"))); // NOI18N
        lbHost.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lbHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lbPuerto.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbPuerto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/server1.png"))); // NOI18N
        lbPuerto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lbPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        getContentPane().add(tfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 200, 40));

        tfHost.setText("192.168.1.50");
        getContentPane().add(tfHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 200, 40));

        tfPuerto.setText("9999");
        getContentPane().add(tfPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 200, 40));

        btAceptar.setBackground(new java.awt.Color(255, 0, 0));
        btAceptar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btAceptar.setForeground(new java.awt.Color(255, 0, 0));
        btAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/business_1.png"))); // NOI18N
        btAceptar.setText("Iniciar sesión");
        btAceptar.setContentAreaFilled(false);
        btAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/business_1.png"))); // NOI18N
        btAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/business_2.png"))); // NOI18N
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 200, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        
        
    }//GEN-LAST:event_btAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new ConfiguracionSala().setVisible(true);
            }
        });
    }

    
    //-----------------------Getters y Setters-----------------------------------
     public String getUsuario()
    {
        return this.tfUsuario.getText();
    }
    
    public String getHost()
    {
        return this.tfHost.getText();
    }
    
    public int getPuerto()
    {
        return Integer.parseInt(this.tfPuerto.getText());
    }
    
    //--------------------------------------------------------------------------
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JLabel lbHost;
    private javax.swing.JLabel lbPuerto;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JTextField tfHost;
    private javax.swing.JTextField tfPuerto;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables

}
